apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-eureka
  namespace: studio-barber
  labels:
    app: reservas-eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservas-eureka-server
  template:
    metadata:
      labels:
        app: reservas-eureka-server
    spec:
      containers:
        - name: reservas-eureka-server
          # nombre local de la imagen -> eureka-server-local:latest (igual siempre )
          image: us-central1-docker.pkg.dev/studiobarber-480215/repo-eureka/eureka-server:v1.0.0
          imagePullPolicy: Always  # nos aseguramos que siempre use la ultima version de la imagen
          ports:
            - containerPort: 8761
              protocol: TCP

# cambios en el codigo = nueva imagen = nueva version vX.0.0
# pasos para subir a Artifact Registry
# 1. docker build -t eureka-server-local:latest . -> contruir imagen local
# 2. docker tag eureka-server-local:latest us-central1-docker.pkg.dev/studiobarber-480215/repo-eureka/eureka-server:v1.0.1 -> tag para subir a AR
# 3. docker push us-central1-docker.pkg.dev/studiobarber-480215/repo-eureka/eureka-server:v1.0.0 -> subir imagen